server:
  port: 8090

spring:
  application:
    name: notification-service

  threads:
    virtual:
      enabled: true

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000ms
          max-attempts: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
